name: afish-ux
favicon: null
layout_spectrum: 1
typography_spectrum: 0.07127
title: UX + IA Portfolio of Anneliese Marek Fish
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebebeb'
    - '#262122'
    - '#f6004f'
    - '#ca7845'
    - '#48c1e2'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
